
# app_name = ENV["APP_NAME"]

default_platform(:android)
platform :android do
  desc "generate build"
  lane :build do
       ruby_version
  end
  lane :build do
    gradle(
      task: "clean",
      project_dir: "./android/"
    )
  end
end
